### ISSUE TITLE
2 - 1 About us page

### ISSUE THREAD

**Issue by Toinne** [hyf-Group2-fp/Just4Giving#56]
# Summary

Create a page where you can find information about the team. See the design on figma.
This feature is created on the branch `2-aboutus`.

### Acceptance criteria

- Create the about us page on the route `/about-us`

---
## redo
redo of PR https://github.com/hyf-Group2-fp/Just4Giving/pull/75
This feature is created on the branch `2-aboutus-update`.

![About page](https://user-images.githubusercontent.com/979362/119331685-f01d7000-bc87-11eb-8149-cb931a79090c.png)

**Comment by bermarte** [comment]
@bhargavkumar7031 Thanks for your interest! We will talk with Anthony, we will explain what we are doing to better understand what is this project about.
